    version: "3.3"

    services:
       app:
          build:
              context: app/docker/develop/nginx
          ports:
            - 81:80
          volumes:
            - ./app:/app
          networks:
             default:
               ipv4_address: 172.28.0.200

    networks:
       default:
         ipam:
           driver: default
           config:
             - subnet: 172.28.0.0/16

